# Generated by Django 5.0.3 on 2024-07-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_remove_errorrecord_fail_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorrecord',
            name='cp_nums',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='errorrecord',
            name='radar',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='errorrecord',
            name='status',
            field=models.CharField(choices=[('ongoing', 'ongoing'), ('finish', 'finish')], default='ongoing', max_length=10),
        ),
        migrations.AlterField(
            model_name='board',
            name='status',
            field=models.CharField(choices=[('testing', 'testing'), ('pause', 'pause'), ('damage', 'damage'), ('cancel', 'cancel'), ('cut', 'cut'), ('archived', 'archived')], default='testing', max_length=10),
        ),
        migrations.AlterField(
            model_name='errorrecord',
            name='fail_message',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='errorrecord',
            name='remark',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.RemoveField(
            model_name='errorrecord',
            name='test_record',
        ),
        migrations.AddField(
            model_name='errorrecord',
            name='test_record',
            field=models.ManyToManyField(related_name='error_records', to='board.testrecord'),
        ),
    ]
